[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "evolutor/__init__.py"

[project]
name = "evolutor"
readme = "README.md"
description = "Dummy package for analytical IBS evolution"
authors = [
    { name = "Felix Soubelet", email = "felix.soubelet@github.com" }
]
dynamic = ["version"]
requires-python = ">=3.10"

dependencies = [
    "numpy >= 2.0 , < 3.0",
    # These bring the IBS convention change
    # Pinned to make sure evolution formula
    # is correct (it is for amplitude rates)
    "xtrack >= 0.80.0 , <1.0",
    "xfields >= 0.23.0 , <1.0",
]

[project.optional-dependencies]
fast = [
    "numba >= 0.60.0",
]
examples = [
    "matplotlib",
]
cli = [
    "evolutor[examples]",
    "typer",
]

[project.scripts]
evolutor = "evolutor.__main__:app"  # works for 'uv tool install'

# ----- Dev Tools Configuration ----- #

[tool.isort]
atomic = true
ensure_newline_before_comments = true
filter_files = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
known_first_party = "evolutor"
known_third_party = "pytest"
line_length = 100
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
profile = "black"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.ruff]
exclude = [
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".tox",
  ".venv",
  "_build",
  "buck-out",
  "build",
  "dist",
]

# Assume Python 3.10+
target-version = "py310"

# Same as black
line-length = 100
indent-width = 4

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
ignore = [
  "E501",     # line-too-long
  "FBT001",   # boolean-type-hint-positional-argument
  "FBT002",   # boolean-default-value-positional-argument
  "PT019",    # pytest-fixture-param-without-value (but suggested solution fails)
  "RUF100",   # detects unused noqa but is wrong
  "PLR0913",  # Expects no more than 5 arguments per function, too low
  "PLR0915",  # Expects no more than 50 statements per function, too low
]

extend-select = [
    "A",        # Detect shadowed builtins
    "E",        # PyCodeStyle errors
    "F",        # Pyflakes rules
    "I",        # Sort imports properly
    "N",        # enforce naming conventions, e.g. ClassName vs function_name
    "W",        # PyCodeStyle warnings
    "C4",       # Catch incorrect use of comprehensions, dict, list, etc
    "FA",       # Enforce from __future__ import annotations
    "PD",       # Good pandas practices
    "PL",       # Pylint rules
    "PT",       # Enforce pytest conventions
    "TC",       # Enforce importing certain types in a TYPE_CHECKING block
    "UP",       # Warn if certain things can changed due to newer Python versions
    "ARG",      # Detect unused arguments
    "BLE",      # disallow catch-all exceptions
    "DTZ",      # Good datetime practices
    "FBT",      # detect boolean traps
    "FLY",      # Prefer idiomatic expressions over string joins
    "ICN",      # Use common import conventions
    "ISC",      # Good use of string concatenation
    "LOG",      # Good logging practices
    "NPY",      # Some numpy-specific things
    "PIE",      # No pointless statements
    "PTH",      # Use pathlib instead of os.path
    "RET",      # Good return practices
    "RUF",      # Ruff specific rules
    "SIM",      # Common simplification rules
    "TID",      # Some good import practices
    "TRY",      # Good try/except practices
    "FURB",     # Refurbishing rules
    "PERF",     # Good performance practices
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
